"""Generate the TypeScript exercise maps from the Python source of truth.

The Python mapper is the canonical table used by the production engine. The
TypeScript package ships a copy for the web app, so this script keeps both
copies deterministic and lets CI catch drift before the two upload paths start
producing different FIT metadata.

Usage:
    python scripts/gen_typescript_map.py
    python scripts/gen_typescript_map.py --check
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PYTHON_MAP = REPO / "src/hevy2garmin/mapper.py"
PYTHON_TEMPLATE_MAP = REPO / "src/hevy2garmin/template_map.py"
TYPESCRIPT_MAP = REPO / "typescript/src/exercise-map.ts"


def _python_mapping(path: Path, name: str) -> dict[str, list[int]]:
    tree = ast.parse(path.read_text())
    for node in ast.walk(tree):
        target = node.target if isinstance(node, ast.AnnAssign) else None
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
        if isinstance(target, ast.Name) and target.id == name:
            value = ast.literal_eval(node.value)
            return {key: list(pair) for key, pair in value.items()}
    raise RuntimeError(f"could not find {name} in {path}")


def _typescript_mapping(text: str, name: str) -> dict[str, list[int]]:
    match = re.search(
        rf"export const {name}: Record<string, \[number, number\]> = (\{{.*?\}});",
        text,
        re.S,
    )
    if not match:
        raise RuntimeError(f"could not find {name} in {TYPESCRIPT_MAP}")
    return json.loads(match.group(1))


def _render(mapping: dict[str, list[int]], template: dict[str, list[int]]) -> str:
    return (
        "/** Exercise → Garmin FIT (category, subcategory) maps.\n"
        " * Generated by scripts/gen_typescript_map.py from the Python source of truth.\n"
        " * Do not edit by hand; run the generator instead. */\n"
        f"export const HEVY_TO_GARMIN: Record<string, [number, number]> = "
        f"{json.dumps(mapping, ensure_ascii=False, separators=(', ', ': '))};\n"
        f"export const TEMPLATE_TO_GARMIN: Record<string, [number, number]> = "
        f"{json.dumps(template, ensure_ascii=False, separators=(', ', ': '))};\n"
    )


def main() -> int:
    python_map = _python_mapping(PYTHON_MAP, "HEVY_TO_GARMIN")
    template_map = _python_mapping(PYTHON_TEMPLATE_MAP, "TEMPLATE_TO_GARMIN")
    current = TYPESCRIPT_MAP.read_text()

    if "--check" in sys.argv[1:]:
        ts_map = _typescript_mapping(current, "HEVY_TO_GARMIN")
        ts_template = _typescript_mapping(current, "TEMPLATE_TO_GARMIN")
        if ts_map != python_map or ts_template != template_map:
            print("TypeScript exercise maps are out of date; run the generator.", file=sys.stderr)
            return 1
        print(f"TypeScript maps are up to date ({len(python_map)} names, {len(template_map)} templates).")
        return 0

    rendered = _render(python_map, template_map)
    TYPESCRIPT_MAP.write_text(rendered)
    print(f"wrote {TYPESCRIPT_MAP.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
